{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "k8s-application-template.fullname" . }}
  labels:
    {{- include "k8s-application-template.labels" . | nindent 4 }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.url }}
  rules:
    - host: {{ .Values.ingress.url }}
      http:
        paths:
        - backend:
            service:
              name: {{ include "k8s-application-template.fullname" . }}
              port:
                name: http
          path: /
          pathType: Prefix
{{- end }}
