{{- if .Values.networkPolicyDenyAll.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "k8s-application-template.fullname" . }}-deny-all
spec:
  podSelector:
    matchLabels:
      {{- include "k8s-application-template.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress: []
{{- end }}
