apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-application-template.fullname" . }}
  labels:
    {{- include "k8s-application-template.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "k8s-application-template.selectorLabels" . | nindent 4 }}
